### ISSUE TITLE
Cannot retreive room ID - empty

### ISSUE THREAD

**Issue by S474N** [andreypopov/node-red-contrib-miio-roborock#17]
** Describe issue **
I used your examples - Homekit. If I clicked on "Get room mapping", then answer in debug is always "empty". Tested with Roborock on charger, in cleaning, but nothing changes.

If i tested node with "Start room cleaning" and in Payload have "1" (or 2, 3, etc.), then the Roborock said "Start room cleaning", went from charger and in next two seconds said "Cleaning complete" and went back to charger.

** Hardware / Software **
  - raspberry 4   
  - version of deconz gateway: [2.05.80 / 14. 8. 2020] 
  - version of node-red-contrib-deconz: [1.2.0]
  - Roborock: [S5 Max]

**Comment by andreypopov** [comment]
Did you create rooms in MiHome ?

**Comment by andreypopov** [comment]
![2020-09-15_15-08-16](https://user-images.githubusercontent.com/1624839/93208512-5949fc80-f765-11ea-8375-63852e94b279.png)

**Comment by S474N** [comment]
Yes, of course, in Xiaomi Home (on iOS is only XH or Roborock app). Have different rooms and obviously using it (for example only cleaning bathroom or bedroom). 

And yes, tested also this imported examples and array[0].

**Comment by andreypopov** [comment]
I dont know. works fine for my s5 max
Checked example for homekit, also shows result.

**Comment by S474N** [comment]
Have different room colors in map, every room has his own number and I can set in left down corner, which room will be cleaned. Nothing else is configurable on iOS.

Which version of firmware do you have? I have 3.5.8_0876

And If I understand, one of your room numbers is 27700101488?

**Comment by andreypopov** [comment]
3.5.8_0876
no, room id is 25.
![2020-09-15_15-35-29](https://user-images.githubusercontent.com/1624839/93210891-1b4ed780-f769-11ea-884e-6d6fb057898d.png)

**Comment by eschava** [comment]
In my case "get room mapping" command returned an empty list until I gave names to all rooms

**Comment by S474N** [comment]
@eschava you have right! Have only rooms as numbers, now added Names and array is here :) 

BTW how can I decode, which room is which? :)

And last question - where can I read the values of rectangle for zone cleaning?

**Comment by andreypopov** [comment]
Send command to clean room, check in MiHome location. 
Try to send vacuum to coordinates from example, check point in MiHome, then correct values.

**Comment by steuerzentrale** [comment]
I just downloaded the miio-roborock contrib and want to say thank you! I love how easy it is to use. 

Roborock S7 firmware 4.1.5_1196
Nodered v2.0.5 on Home Assistant OS 6.2 / core-2021.8.8
activated multiple foors/stories in the Xiaomi Home app

Actually I am struggling with getting room-ids and found this thread. I live in a house with 3 floors/stories. In the Mi Home app I created a map for each floor and gave the rooms a name, as it is necessary to recognize them via get room mapping.
![IMG_2503](https://user-images.githubusercontent.com/75168550/130319121-03ea24d4-816e-4f5d-945c-86332e128fc9.PNG)
![IMG_2504](https://user-images.githubusercontent.com/75168550/130319126-70fa49c3-92cc-4fc1-acf9-9230dd5d3bdb.PNG)
![IMG_2506](https://user-images.githubusercontent.com/75168550/130319160-26513bc9-4f1f-4922-82dd-b0405bc14626.PNG)


I placed the vaccum in the living room which has two rooms called Wohnzimmer and Küche. Via the command get room mapping I receive the following output:
<img width="318" alt="Bildschirmfoto 2021-08-21 um 12 24 43" src="https://user-images.githubusercontent.com/75168550/130318939-fe83b67d-a649-40b7-8900-50cdb8241d78.png">

If I place the vacuum in the first floor called 1OG, it still says 16 and 17, but it seems that the room numbers 540001031257 & 540001031327 were recognized.

<img width="320" alt="Bildschirmfoto 2021-08-21 um 12 26 28" src="https://user-images.githubusercontent.com/75168550/130318945-e2f6aded-a9cc-46c9-88e0-167e4e0af9a5.png">

Am I doing something wrong? My goal is to retrieve each room id in order to create nodered-flows. I hope its ok to reopen this thread, as it could help others :)

many thanks for your support

Andrew

**Comment by jerome83136** [comment]
Hi,
For those that cannot have the "room naming" option in the Xiaomi Home APP (like me):
It seems related to the robot's firmware. On my case I have 2 robots connected to the same APP:
- Roborock S5
- Roborock S7 Pro Ultra
For the S7, room naming option is there in the APP; but it is not for the S5

Anyway; I managed to do room cleaning on both robots.
For the S5 "get room mapping" in Node Red doesn't work because it requires a name on rooms in the Xiaomi Home APP.
But "start room cleaning" works by "guessing" the room ID and sending it trought Node Red.

On my case; I tried the room ID "16" and in the Xiaomi Home APP I could see it corresponds to my kitchen.
So I tried all possible room IDs until I got all of them.

So: naming rooms in the Xiaomi Home APP is not mandatory to use the "room cleaning" feature from this node :)

Hope it will help
Regards
